---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podlist
spec:
  replicas: 1
  selector:
    matchLabels:
      app: podlist
  template:
    metadata:
      labels:
        app: podlist
    spec:
      serviceAccountName: podlist
      containers:
        - image: okteto.dev/podlist:latest
          name: podlist
---
apiVersion: v1
kind: Service
metadata:
  name: podlist
spec:
  type: ClusterIP
  ports:
  - name: "podlist"
    port: 8080
  selector:
    app: podlist
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: podlist
  annotations:
    dev.okteto.com/generate-host: podlist
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: podlist
            port:
              number: 8080
        path: /
        pathType: ImplementationSpecific
---
apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  labels:
    app: podlist
  name: podlist
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: podlist
  name: podlist
rules:
  - apiGroups:
    - ""
    resources:
    - pods
    verbs:
    - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: podlist
  name: podlist
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: podlist
subjects:
  - kind: ServiceAccount
    name: podlist
